version: 2
jobs: 
  build:
    docker:
      - image: circleci/openjdk:8
    steps:  
      - checkout
      - run: sudo apt-get update; sudo apt-get install wamerican
      - restore_cache:
          key: build-libs
      - run: ant build
      - save_cache:
          key: build-libs
          paths: 
           - build/libs
      - run: 
          name: Running Tests
          command: |
              case $CIRCLE_NODE_INDEX in 
                0) ant test -Dtest.runners=2;;
                1) ant long-test ;;
                2) ant test-compression ;;
                3) ant stress-test ;;
              esac
      - run: |
         mkdir -p ~/junit/
         find ./build/test/output/ -iname "*.xml" -exec cp {} ~/junit/ 
      - store_test_results: 
         path: ~/junit
      - store_artifacts: 
         path: ~/junit


